### ISSUE TITLE
Cancelling an order causes an endless loop

### ISSUE THREAD

**Issue by bYemma** [Nets-eCom/oxid7#2]
https://github.com/Nets-eCom/oxid7/blob/847a2b15f85a52c10cc715793730f1695d9945b7/Extend/Application/Model/Order.php#L256-L262

Method calls itself again and again.
I think the intention was to call the parent method.

How to reproduce:
1. Choose NexiCheckout as payment method.
2. Submit the order to get to the Nexi payment page
3. Cancel the order to trigger the cancelOrder method and the infinite loop.

**Comment by bYemma** [comment]
The cause was probably a refactor (https://github.com/Nets-eCom/oxid7/commit/1fe7b635bb304c57ac05684d5c76f819d97b96a5), where the method was renamed.

In the OXID 6 module the method was named `netsCancelOrder()` and calling `$this->cancelOrder()` did not create a loop:
https://github.com/Nets-eCom/oxid6_easy/blob/f0c7b331074b45fd5d2acafe713939c38ca13b85/extend/Application/Model/Order.php#L259C5-L265C6

**Comment by pk-nexigroup** [comment]
Hey @bYemma. Thank you for your contribution. Since this is our release repository, we will push changes from our side. We will close this issue, and create a release with the fix.
