### ISSUE TITLE
checkOrderExist fails every time

### ISSUE THREAD

**Issue by bYemma** [Nets-eCom/oxid7#4]
https://github.com/Nets-eCom/oxid7/blob/3bf119d2531efeb41d8f5c36f6c2e0a54770d3c7/Extend/Application/Model/Order.php#L432

This property is not defined. `blIsNetsHostedModeReturn` was refactored to `isHostedModeReturn`

This is the correct version:
```php
if ($this->isHostedModeReturn === false) {
```

This results in a broken check whether a order exists already or not. So you can trigger the finalizeOrder twice by double click on the submit order button.

**Comment by pk-nexigroup** [comment]
Hey @bYemma. Thank you again for your contribution. We have introduced release with the change.
